### ISSUE TITLE
Security state use case

### ISSUE THREAD

**Issue by leplatrem** [mozilla/remote-settings#23]
- [ ] https://bugzilla.mozilla.org/show_bug.cgi?id=1437692

**Comment by mostlygeek** [comment]
update: 

[meeting notes](https://docs.google.com/document/d/11yecbiP-XRt8AJDqNtbQQaUr6iAPzMm8Ygrjqq-6jqs/edit?usp=sharing)

tl;dr: 

- they want and need their own buckets  / signing keys for things
- they are ok with the idea of a `main` bucket.  They can't use it since they need a different signing certificate for their data, which is more critical.
- the new V2 APIs looks good and they are looking forward to using them

**Comment by mostlygeek** [comment]
We can close this issue and track any new work in the bug in the description.  We can make a project card for it later to track the bug.
